package game.ui.commands;

public enum CommandName {
	// MAIN MENU COMMANDS
	NEW_CHESSBOARD, 
	FILE_LOADER, 
	
	// FILE LOADER COMMANDS
	GET_FILE_NAMES,
	LOAD_CHESSBOARD_FROM_FILE,
	
	// CHESSBOARD DISPLAY COMMANDS
	GET_CHESSBOARD,
	PUT_FIGURE,
	TAKE_FIGURE,
	UPDATE_CHESSBOARD_STATE,
	
	// COMMANDS TO BE USED BY ALL SEGMENTS
	EXIT,
	GO_BACK;
}
